name: Continous Integration

on:
  pull_request:
    branches:
      - develop
      
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

  goodbye:
    runs-on: ubuntu-latest

    steps:
      - name: Print Goodbye World
        run: echo "Goodbye, World!"

  build:
    runs-on: ubuntu-latest
    needs: goodbye
    env: 
      DISABLE_ESLINT_PLUGIN: true
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16.18.0"
      
      - name: Run Build
        run: |
          npm install
          npm run build
